name: build and test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach git head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic mvg-info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "if master: fail if there is already a tag for this version"
        run:  |
          . <(java -jar ~/buildTools.jar)
          errorIfMasterAndVersionTagExists

      - name: "prepare"
        run:  |
          cat <<EOF >build.properties
          jdk.home.11=$JAVA_HOME
          path.variable.mps_home=./MPS
          EOF

      - name: "determine versionExtra and versionStamp"
        run:  |
          branch="${GITHUB_REF#refs/heads/}"
          if [[ "$branch" == master ]]; then
            versionExtraArg="-DversionExtra="
            versionStampArg="-DversionStamp="
          elif [[ "$branch" == develop ]]; then
            versionExtraArg="-DversionExtra=beta"
            versionStampArg=
          else
            versionExtraArg="-DversionExtra=alpha"
            versionStampArg=
          fi
          echo "::set-env name=versionExtraArg::$versionExtraArg"
          echo "::set-env name=versionStampArg::$versionStampArg"

      - name: "(re)generate some files"
        run:  |
          . <(java -jar ~/buildTools.jar)
          generateAll
          correctEols
          correctHeaders header

      - name: "download dependencies (MPS and jars from pom)"
        run:  |
          . <(java -jar ~/buildTools.jar)
          . project.sh
          getAllDependencies ${{ secrets.GITHUB_TOKEN }} "${{ secrets.SCALEWAY_ACCESS_KEY }}" "${{ secrets.SCALEWAY_SECRET_KEY }}"
          installMps "$mpsDir" "$mpsVersion"

          mpsUntilDefault="$(sed -q 's/^mps[.]build[.]number=MPS-//p' "$mpsDir/build.properties")"
          sed 's/ since-build="[^"]*"/ since build="'"$mpsSince"'"/' *.xml
          sed 's/ until-build="[^"]*"/ until build="'"${mpsUntil:-$mpsUntilDefault}"'"/' *.xml

      - name: "push changes back to github"
        run:  |
          . <(java -jar ~/buildTools.jar)
          pushBackToGithub "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com" "adjusted files [by github actions]"

      - name: "runtime: build"
        run:  ant

      - name: "runtime: test"
        run:  |
          if ! ant test; then
            for i in TEST-*.xml; do
              echo "=============== $i"
              sed "s/^/>> /" $i
            done
            exit 42
          fi

      - name: "runtime: generate javadoc"
        run:  ant javadoc

      - name: "dclare-plugin: build"
        run:  |
          . <(java -jar ~/buildTools.jar)
          . project.sh
          action() {
            ant -Dmps_home="$mpsDir" "-Dversion=$version" "$versionExtraArg" "$versionStampArg" -f mps_build.xml cleanSources clean generate build
          }
          doubleBuild action mps_build.xml

      - name: "unzip for actions/upload-artifact"
        run:  |
          # the subsequent actions/upload-artifact step would re-zip the zip, so we unzip and the action below will rezip...
          mkdir build/artifacts/DclareForMPS/DclareForMPS
          cd build/artifacts/DclareForMPS/DclareForMPS
          unzip ../DclareForMPS.zip

      - name: "if master: tag with version"
        run:  |
          . <(java -jar ~/buildTools.jar)
          setVersionTagIfMaster "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com"

      - name: "publish action-artifact zip"
        uses: actions/upload-artifact@v1
        with:
          name: DclareForMPS
          path: build/artifacts/DclareForMPS/DclareForMPS

      - name: "Upload to JetBrains"
        uses: ModelingValueGroup/upload-jetbrains-plugin-action@master
        with:
          file    : "build/artifacts/DclareForMPS/DclareForMPS.zip"
          hubToken: "${{ secrets.JETBRAINS_PUBLISH_TOKEN }}"
          pluginId: "13797"
          trace   : true
