on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+beta[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]

name: Create Release

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: create beta release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name    : ${{ github.ref }}
          release_name: beta release ${{ github.ref }}
          draft       : false
          prerelease  : true
          body: |
            Changes in this Release
            - First Change
            - Second Change
