on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+alpha[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]

name: Create Release

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: not published for now
        run:  :
